//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDatos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Conexion : global::System.Configuration.ApplicationSettingsBase {
        
        private static Conexion defaultInstance = ((Conexion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Conexion())));
        
        public static Conexion Default {
            get {
                return defaultInstance;
            }
        }
    }
}
